name: Python Static Analysis v+

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
    - name: Run static analysis
      run: |
        flake8 .
        pylint .
